### ISSUE TITLE
[Bug]: arclight的mc版本不应出现非x.x.x版本号

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [MCSLTeam/MCSL-Sync-Backend#4]
![image](https://github.com/user-attachments/assets/f863606e-2e38-44b1-971c-bc8d280d351d)
[core.go](https://gist.github.com/Mr-Ao-Dragon/e599ff2b9c55c58c085d45e16e72766b)
[core_test.go](https://gist.github.com/Mr-Ao-Dragon/b67febe5f314ce2838309fee4a152a8a)
[list.go](https://gist.github.com/Mr-Ao-Dragon/04a1485cd6cc4ee1ae8ba5526b881c19)
[info/model.go](https://gist.github.com/Mr-Ao-Dragon/d237451c8421f834615b11956c228de1)
[setup/model.go](https://gist.github.com/Mr-Ao-Dragon/7c370b8cc71bbb7c3022579288561c4d)

**Comment by LxHTT** [comment]
官方就是这样写的，自己替换格式化。
